---
###
# Playbook will restore a Plex Media Server
###

- hosts: plex
  gather_facts: false
  tasks:
  - name: Create Plex Dir
    file:
      state: directory
      path: /plex
      mode: 0755

  - name: Create Library Dir
    file:
      state: directory
      path: /var/lib/plexmediaserver
      mode: 0755

  - name: Install NFS Utils
    dnf:
      name: nfs-utils
      state: latest

  - name: Mount plex dir
    mount:
      path: /plex
      src: "nas01.kywa.io:/volume1/plex"
      fstype: nfs
      state: mounted

  - name: Open Plex Server Port on Firewall
    firewalld:
      port:  "32400/tcp"
      permanent: yes
      state: enabled

  - name: Install Plex RPM
    shell: rpm -i /plex/pms-latest.rpm
    ignore_errors: true

  - name: Restore Plex Library data
    unarchive:
      remote_src: yes
      src: "/plex/libbackup.tgz"
      dest: "{{ plex_library_dir }}"

  - name: Force redownload of Codecs
    copy:
      remote_src: true
      src: "/var/lib/plexmediaserver/Library/Application\ Support/Plex\ Media\ Server/Codecs"
      dest: /tmp/Codecs
    ignore_errors: true

  - name: Symlink Codecs
    file:
      state: link
      src: /tmp/Codecs
      dest: "/var/lib/plexmediaserver/Library/Application\ Support/Plex\ Media\ Server/Codecs" 
    ignore_errors: true

  - name: SELinux Restorecon
    shell: restorecon -R /var/lib/plexmediaserver

  - name: Restart Plex Service
    systemd:
      name: plexmediaserver
      state: restarted
