---
###
#
# Playbook will backup an Plex's library data and systemd Service. 
#
###

- hosts: plex
  gather_facts: false
  tasks:
  - name: backup Systemd unit
    copy:
      remote_src: yes
      src: "{{ systemd_unit_file }}"
      dest: /plex/plexmediaserver.service

  - name: Get Plex RPMs
    find:
      paths: "/root"
    register: found_files
  
  - name: Get latest Plex RPM
    set_fact:
      latest_file: "{{ found_files.files | sort(attribute='mtime',reverse=true) | first }}"

  - name: backup latest rpm
    copy:
      remote_src: yes
      src: "{{ latest_file.path }}"
      dest: /plex/pms-latest.rpm

  - name: move old backup
    shell: mv /plex/libbackup.tgz /plex/libbackup.tgz-old

  - name: archive and copy plex library
    archive:
      path: "{{ plex_library_dir }}"
      dest: "/plex/libbackup.tgz"
      format: gz
      mode: 0644

  - name: remove old backup
    file:
      path: "/plex/libbackup.tgz-old"
      state: absent
