# Place all RHV/oVirt specific variables here
ovirt_cluster: Default
ovirt_config_file: "" # Leave blank unless you know what you are doing

# Configure the hosted_engine host_vars for these variables
ovirt_url: "{{ hostvars[groups['hosted_engine'][0]].ovirt_url }}"
ovirt_username: "{{ hostvars[groups['hosted_engine'][0]].ovirt_username }}"
ovirt_password: "{{ hostvars[groups['hosted_engine'][0]].ovirt_password }}"

# Obtain this from RHV using CURL (see OCP4 documentation https://docs.openshift.com) and the RHV-M WebUI
ovirt_vnic_profile_id: "0000000a-000a-000a-000a-000000000398"
ovirt_cluster_id: fc5cde98-844e-11ec-91b7-00163e6ed550
ovirt_network_name: ovirtmgmt
ovirt_storage_domain_id: 233f8ff2-f94e-44e5-b187-185eae615e7d
