---
- hosts: openshift
  gather_facts: false
  tasks:

  - name: ovirt-auth
    import_role:
      name: ovirt

  - name: create-vm
    import_role:
      name: ovirt
      tasks_from: create-vm.yml

  - name: deploy-cluster
    import_role:
      name: okd
      tasks_from: deploy-cluster.yml

  - name: post install tasks
    import_role:
      name: okd
      tasks_from: post-install.yml
