---
- name: Install Java
  dnf:
    name: "java-{{ minecraft_java_version }}-openjdk"
    state: installed

- name: Install jq
  block:
    - name: Check and Set jq path
      stat: 
        path: /usr/bin/jq
      register: jq_installed
    
    - name: Grabbing jq
      shell: curl -o /usr/bin/jq -sL https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64 && chmod +x /usr/bin/jq
      when: jq_installed.stat.exists != true

- name: Obtain Minecraft Server jar file
  block:
    - name:  Grabbing specified version of Minecraft Server
      shell: |
        curl -o {{ minecraft_directory }}/server.jar $(curl `curl -sL https://launchermeta.mojang.com/mc/game/version_manifest.json | jq -r '.versions[] | select (.id == "{{ minecraft_version }}") | .url'` | jq -r '.downloads.server.url')
      when: minecraft_version != "latest"
      notify: restart minecraft
    
    - name: Grabbing latest version of Minecraft Server
      shell: |
        curl -o {{ minecraft_directory }}/server.jar $(curl `curl -sL https://launchermeta.mojang.com/mc/game/version_manifest.json | jq -r '.latest.release as $release | .versions[] | select(.id == $release) | .url'` | jq -r '.downloads.server.url')
      when: minecraft_version == "latest"
      notify: restart minecraft

    - name: Set owner of server.jar
      file:
        path: "{{ minecraft_directory }}/server.jar"
        owner: "{{ minecraft_user }}"
        group: "{{ minecraft_group }}"
