---
- name: Install required tools
  dnf:
    name: "{{ rpm_packages }}"
    state: present

# Leaving commented tasks below
# was used to build dnsplugin
    #  loop:
    #    - git
    #    - nfs-utils
    #    - go
    #    - make
    #    - containernetworking-plugins
    #    - dnsmasq

    #- name: Group install for devtools
    #  dnf:
    #    name: '@Development Tools'
    #    state: present
