---

- name: Install pre-requisites
  include_tasks: dnsname_plugin_pre_req.yml
  when: container_dev == true

- name: Container Plugin setup
  include_tasks: dnsname_plugin.yml
  when: container_dev == true
