# OKD Specific
openshift_ansible_dir: /Users/kylewalker/Working/openshift-ansible
okd_prerequisite: /Users/kylewalker/Working/openshift-ansible/playbooks/prerequisites.yml
okd_install: /Users/kylewalker/Working/openshift-ansible/playbooks/deploy_cluster.yml
okd_scaleup: /Users/kylewalker/Working/openshift-ansible/playbooks/openshift-node/scaleup.yml
okd_release: "release-3.11"
deployment_type: origin
openshift_deployment_type: origin
openshift_disable_check: docker_storage,docker_storage_driver,memory_availability,docker_image_availability,disk_availability
ansible_service_broker_install: false
openshift_release: '3.11'
openshift_image_tag: 'v3.11'
containerized: true
osm_use_cockpit: true


openshift_node_groups:
  - name: node-config-master 
    labels:
      - 'node-role.kubernetes.io/master=true' 
    edits: [] 

  - name: node-config-infra
    labels:
      - 'node-role.kubernetes.io/infra=true'
    edits: []

  - name: node-config-compute
    labels:
      - 'node-role.kubernetes.io/compute=true'
    edits: []

  - name: node-config-nvidia
    labels:
      - 'node-role.kubernetes.io/compute=true'
      - 'node-role.kubernetes.io/nvidia=true'
      - 'openshift.com/gpuaccelerator=true'
    edits: []

# Auth
openshift_master_identity_providers: [{'name': 'htpasswd_auth', 'login': 'true', 'challenge': 'true', 'kind': 'HTPasswdPasswordIdentityProvider'}]

# Networking
os_sdn_network_plugin_name: "redhat/openshift-ovs-multitenant"

# Registry
openshift_hosted_registry_replicas: 1
openshift_hosted_registry_selector: "node-role.kubernetes.io/infra=true"

# Metrics
openshift_metrics_image_version: "v3.11"
openshift_metrics_selector: {"node-role.kubernetes.io/infra":"true"}
openshift_metrics_cassandra_nodeselector: "{{ openshift_metrics_selector }}"
openshift_metrics_heapster_nodeselector: "{{ openshift_metrics_selector }}"
openshift_metrics_hawkular_nodeselector: "{{ openshift_metrics_selector }}"
openshift_metrics_hawkular_hostname: hawkular-metrics.okd.kywa.io
openshift_metrics_cassandra_storage_type: pv
openshift_metrics_cassandra_pvc_size: 10Gi
openshift_metrics_cassandra_replicas: 1
openshift_metrics_hawkular_replicas: 1

# Router
openshift_hosted_router_selector: "node-role.kubernetes.io/infra=true"
openshift_hosted_router_certificate: {"certfile": "{{ inventory_dir }}/../files/certs/okd.kywa.io.crt", "keyfile": "{{ inventory_dir }}/../files/certs/okd.kywa.io.key", "cafile": "{{ inventory_dir }}/../files/certs/okd.kywa.io.crt"}

# Console
openshift_web_console_install: true
openshift_console_install: true

# Masters
openshift_master_api_port: 443
openshift_master_console_port: 443
openshift_master_cluster_hostname: console.okd.kywa.io
openshift_console_hostname: cluster-console.okd.kywa.io
openshift_master_cluster_public_hostname: console.okd.kywa.io
openshift_master_default_subdomain: okd.kywa.io
openshift_master_bootstrap_auto_approve: true

# Infra

# Compute
