# OKD Specific
openshift_ansible_dir: /home/kwalker/Working/openshift-ansible
okd_prerequisite: /home/kwalker/Working/openshift-ansible/playbooks/prerequisites.yml
okd_install: /home/kwalker/Working/openshift-ansibleplaybooks/deploy_cluster.yml
okd_release: "release-3.11"
deployment_type: origin
openshift_deployment_type: origin
openshift_disable_check: docker_storage,docker_storage_driver,memory_availability,docker_image_availability,disk_availability
ansible_service_broker_install: false
openshift_release: '3.11'
openshift_image_tag: 'v3.11'
containerized: true
osm_use_cockpit: true


openshift_node_groups:
  - name: node-config-master 
    labels:
      - 'node-role.kubernetes.io/master=true' 
    edits: [] 

  - name: node-config-infra
    labels:
      - 'node-role.kubernetes.io/infra=true'
    edits: []

  - name: node-config-compute
    labels:
      - 'node-role.kubernetes.io/compute=true'
    edits: []

# Auth
openshift_master_identity_providers: [{'name': 'htpasswd_auth', 'login': 'true', 'challenge': 'true', 'kind': 'HTPasswdPasswordIdentityProvider'}]

# Networking
os_sdn_network_plugin_name: "redhat/openshift-ovs-multitenant"

# Registry
openshift_hosted_registry_replicas: 1
openshift_hosted_registry_selector: "node-role.kubernetes.io/infra=true"

# Router
openshift_hosted_router_selector: "node-role.kubernetes.io/infra=true"
openshift_hosted_router_create_certificate: true

# Console
openshift_web_console_install: true

# Masters
openshift_master_api_port: 8443
openshift_master_console_port: 8443
openshift_master_cluster_hostname: console.okd.kywa.io
openshift_master_cluster_public_hostname: console.okd.kywa.io
openshift_master_default_subdomain: okd.kywa.io
openshift_master_bootstrap_auto_approve: true

# Infra

# Compute
