---
- name: create vm
  ovirt.ovirt.ovirt_vm:
    wait: true
    timeout: 2400
    auth: "{{ ovirt_auth }}"
    name: "{{ inventory_hostname }}"
    comment: ""
    description: "{{ vm_description | default('') }}"
    template: "{{ ovirt_vm_template }}"
    operating_system: "{{ vm_os }}"
    cluster: "Default"
    cpu_cores: "{{ cpu_core }}"
    cpu_sockets: "{{ cpu_socket }}"
    memory: "{{ max_mem }}GiB"
    memory_guaranteed: "{{ min_mem }}GiB"
    high_availability: false
    state: running
    storage_domain: "{{ ovirt_storage_domain }}"
    clone: true
    disk_format: raw
    cloud_init_persist: true
    cloud_init:
      dns_servers: "{{ dns_servers }}"
      dns_search: "{{ dns_search }}"
      nic_boot_protocol: "{{ boot_protocol }}"
      nic_ip_address: "{{ ipv4_addr }}"
      nic_netmask: "{{ ipv4_netmask }}"
      nic_gateway: "{{ ipv4_def_route }}"
      nic_name: "{{ nic_name }}"
      host_name: "{{ inventory_hostname }}"
      authorized_ssh_keys: "{{ ansible_ssh_key }}"
      regenerate_ssh_keys: true
      user_name: root
      root_password: "{{ root_user_password }}"
  delegate_to: localhost
  register: created_vm

- name: Run Post Install Tasks
  include_tasks: post-install.yml
  when: created_vm is changed
