---
- name: stop vm
  ovirt_vm:
    timeout: 2400
    auth: "{{ ovirt_auth }}"
    name: "{{ inventory_hostname }}"
    state: stopped
  delegate_to: localhost

- name: save cloud-init
  ovirt_vm:
    timeout: 2400
    auth: "{{ ovirt_auth }}"
    name: "{{ inventory_hostname }}"
    cloud_init_persist: true
    cloud_init:
      dns_servers: "{{ dns_servers }}"
      dns_search: "{{ dns_search }}"
      nic_boot_protocol: "{{ boot_protocol }}"
      nic_ip_address: "{{ ipv4_addr }}"
      nic_netmask: "{{ ipv4_netmask }}"
      nic_gateway: "{{ ipv4_def_route }}"
      nic_name: "{{ nic_name }}"
      host_name: "{{ inventory_hostname }}"
      regenerate_ssh_keys: true
      authorized_ssh_keys: "{{ ansible_ssh_key }}"
      root_password: "{{ root_user_password }}"
      user_name: root
  delegate_to: localhost

- name: create storage disk
  ovirt_disk:
    timeout: 2400
    name: "{{ inventory_hostname }}-data"
    activate: no
    format: raw
    size: "{{ data_disk_size }}GiB"
    auth: "{{ ovirt_auth }}"
    storage_domain: "{{ ovirt_storage_domain }}"
    interface: virtio_scsi
    vm_name: "{{ inventory_hostname }}"
    state: present
  delegate_to: localhost
  when: data_disk is defined
  register: add_disk

- name: attach storage disk
  ovirt_disk:
    timeout: 2400
    name: "{{ inventory_hostname }}-data"
    activate: true
    auth: "{{ ovirt_auth }}"
    vm_name: "{{ inventory_hostname }}"
    state: attached
  delegate_to: localhost
  when: data_disk is defined
  register: add_disk

- name: update settings
  ovirt_vm:
    timeout: 2400
    auth: "{{ ovirt_auth }}"
    name: "{{ inventory_hostname }}"
    boot_devices: [ 'hd' ]
    boot_menu: false
    usb_support: false
  delegate_to: localhost

- name: start vm
  ovirt_vm:
    timeout: 2400
    auth: "{{ ovirt_auth }}"
    name: "{{ inventory_hostname }}"
    state: running
  delegate_to: localhost

- name: Run Disk Configuration
  include_tasks: disks.yml
  when: add_disk is changed

- name: Add Firewall Rules
  include_tasks: firewall.yml
  when: firewall_port is defined

- name: package update
  dnf:
    name: "*"
    state: latest
