---
- name: create vm
  ovirt_vm:
    wait: true
    timeout: 2400
    auth: "{{ ovirt_auth }}"
    name: "{{ inventory_hostname }}"
    description: "{{ vm_description | default('') }}"
    template: "{{ ovirt_vm_template }}"
    operating_system: "{{ vm_os }}"
    cluster: "Default"
    cpu_cores: "{{ cpu_core }}"
    cpu_sockets: "{{ cpu_socket }}"
    memory: "{{ max_mem }}GiB"
    memory_guaranteed: "{{ min_mem }}GiB"
    state: present
    storage_domain: "{{ ovirt_storage_domain }}"
    clone: true
    disk_format: raw
    cloud_init_persist: true
    cloud_init:
      dns_servers: "{{ dns_servers }}"
      dns_search: "{{ dns_search }}"
      nic_boot_protocol: "{{ boot_protocol }}"
      host_name: "{{ inventory_hostname }}"
      regenerate_ssh_keys: true
      authorized_ssh_keys: "{{ ansible_ssh_key }}"
      root_password: "{{ root_user_password }}"
      user_name: root
  delegate_to: localhost
  register: created_vm
  retries: 5
  delay: 15
  until: created_vm is not failed

- name: start vm
  ovirt_vm:
    timeout: 2400
    auth: "{{ ovirt_auth }}"
    name: "{{ inventory_hostname }}"
    state: running
  delegate_to: localhost

- name: Wait for VM to be up
  wait_for:
    port: 22
    delay: 30

- name: package update
  dnf:
    name: "*"
    state: latest

- name: stop vm
  ovirt_vm:
    timeout: 2400
    auth: "{{ ovirt_auth }}"
    name: "{{ inventory_hostname }}"
    state: stopped
  delegate_to: localhost

- name: update settings
  ovirt_vm:
    timeout: 2400
    auth: "{{ ovirt_auth }}"
    name: "{{ inventory_hostname }}"
    boot_devices: ['hd']
    boot_menu: false
    usb_support: false
  delegate_to: localhost

- name: Template subversion
  ovirt_template:
    auth: "{{ ovirt_auth }}"
    cluster: "Default"
    name: "{{ ovirt_vm_template }}"
    vm: "{{ inventory_hostname }}"
    version:
      name: updated
  delegate_to: localhost

- name: delete vm
  ovirt_vm:
    timeout: 2400
    auth: "{{ ovirt_auth }}"
    name: "{{ inventory_hostname }}"
    state: absent
  delegate_to: localhost
