---

# ansible-playbook -i inv/hosts playbook/ovirt/create-vm.yml --limit="hostname"

- hosts: all
  gather_facts: false
  tasks:

  - name: ovirt-auth
    import_role:
      name: ovirt

  - name: delete-vm
    import_role:
      name: ovirt
      tasks_from: delete-vm.yml

  collections:
    - ovirt.ovirt
