---

- hosts: all
  gather_facts: false
  tasks:

  - name: copy-backup-script
    copy:
      src: "{{ inventory_dir }}/../files/ovirt-backup.sh"
      dest: /etc/cron.daily/ovirt-backup.sh
      mode: 0755
