---
- hosts: templates
  gather_facts: false
  tasks:

  - name: ovirt-auth
    import_role:
      name: ovirt

  - name: Create Template VM
    import_role:
      name: ovirt
      tasks_from: template.yml
    run_once: true

  collections:
    - ovirt.ovirt
