---

# ansible-playbook -i inventory/filename playbook/ovirt/create-vm.yml --limit="hostname"

- hosts: all
  gather_facts: false
  vars:
    minecraft_install: true
  tasks:
  - name: Install Minecraft
    import_role:
      name: minecraft
