# .bashrc
if [ -f /etc/bashrc ];then
    . /etc/bashrc
fi

# General fun
umask 002
set -o vi

export TERM="xterm-256color"
export EDITOR="vim"

# Aliases
# quality of life things
alias ls='ls -Fh --color=auto'
alias grep='grep --color=auto'

# better process checking
alias psg="ps aux | grep -v grep | grep -i -e VSZ -e"

# show dirs and force dir creation
alias mkdir='mkdir -pv'

# ssh get rid of annoyances
alias ssh='ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no'
alias scp='scp -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no'

# Functions
mcd(){
    mkdir $1
    cd $1
}

# clear screen because i"m lazy
cls(){
    clear
}
