---
- name: Upload node-config
  copy:
    src: node-config-nvidia.yml
    dest: "/tmp/node-config-nvidia.yml"

- name: apply config
  shell: "oc apply -f /tmp/node-config-nvidia.yml"

- name: Upload scc
  copy:
    src: sccg-nvidia.yml
    dest: "/tmp/scc-nvidia.yml"

- name: apply scc
  shell: "oc apply -f /tmp/scc-nvidia.yml"

- name: Upload deviceplugin
  copy:
    src: deviceplugin.yml
    dest: "/tmp/deviceplugin.yml"

- name: apply deviceplugin
  shell: "oc apply -f /tmp/deviceplugin.yml"
