---
- name: create temp inv file
  tempfile:
    state: file
    suffix: ocp-tmp-install
    path: /tmp/
  register: tmp_log
  run_once: true
  delegate_to: localhost

- name: run prerequisites
  command: ansible-playbook -i {{ inventory_file }} --vault-password-file {{ vault_pass_file }} {{ okd_prerequisite }}
  args:
    chdir: "{{ lookup('env', 'PWD') }}"
  environment:
    ANSIBLE_LOG_PATH: "{{ tmp_log.path }}"
  run_once: true
  delegate_to: localhost

- name: run install
  command: ansible-playbook -i {{ inventory_file }} --vault-password-file {{ vault_pass_file }} {{ okd_install }}
  args:
    chdir: "{{ lookup('env', 'PWD') }}"
  environment:
    ANSIBLE_LOG_PATH: "{{ tmp_log.path }}"
  run_once: true
  delegate_to: localhost
