---
- name: Cert update for Red Hat
  shell: |
    openssl s_client -showcerts -servername registry.access.redhat.com -connect registry.access.redhat.com:443 </dev/null 2>/dev/null | openssl x509 -text > /etc/rhsm/ca/redhat-uep.pem
  ignore_errors: yes

- name: make docker dir
  file:
    path: /var/lib/origin/.docker
    state: directory
    mode: '755'

- name: copy registry cred
  copy:
    src: "{{ inventory_dir }}/../files/config.json"
    dest: /var/lib/origin/.docker/config.json
    mode: '600'
