---
- name: temp log
  tempfile:
    state: file
    suffix: scaleup-tmp-log
  register: tmp_log
  run_once: true
  delegate_to: localhost

- debug:
    msg: "Logs are here: {{ tmp_log.path }}"
  run_once: true
  delegate_to: localhost
      
    #- name: run prerequisites
    #  command: ansible-playbook -i {{ inventory_file }} --vault-password-file {{ vault_pass_file }} {{ okd_prerequisite }}
    #  args:
    #    chdir: "{{ lookup('env', 'PWD') }}"
    #  environment:
    #    ANSIBLE_LOG_PATH: "{{ tmp_log.path }}"
    #  run_once: true
    #  delegate_to: localhost

- name: run scaleup
  command: ansible-playbook -i {{ inventory_file }} --vault-password-file {{ vault_pass_file }} {{ okd_scaleup }}
  args:
    chdir: "{{ lookup('env', 'PWD') }}"
  environment:
    ANSIBLE_LOG_PATH: "{{ tmp_log.path }}"
  run_once: true
  delegate_to: localhost
