ansible_ssh_user: root
minecraft_java_version: "17"
minecraft_backup: false
minecraft_restore: false
minecraft_config_change: false
minecraft_user: "minecraft"
minecraft_group: "minecraft"
minecraft_directory: "/opt/minecraft"
minecraft_version: "latest"
minecraft_java_opts: "-Xms512m -Xmx2048m"
