---
- name: systemd_nginx
  systemd:
    name: nginx
    state: started
    enabled: yes

- name: systemd_fail2ban
  systemd:
    name: fail2ban
    state: started
    enabled: yes

- name: restart nginx
  systemd:
    name: nginx
    state: restarted

- name: restart fail2ban
  systemd:
    name: fail2ban
    state: restarted
