---
# Usage: ansible-playbook -i inventory/kywalab playbooks/all/poweroutage.yml

- name: Power Outage preparation
  hosts: vms
  gather_facts: false
  tasks:
  - name: Shutdown VMs
    shell: "shutdown -h now"
    when: inventory_hostname in group(vms)

  - name: oVirt maintenance mode
    shell: "hosted-engine --set-maintenance --mode=global && hosted-engine --vm-shutdown"
    when: inventory_hostname == vhost1.kywa.io

  - name: Pause for hosted-engine
    pause:
      seconds: 60

  - name: shutdown ovirt
    shell: "shutdown -h now"
    when: inventory_hostname == vhost1.kywa.io

  - name: shutdown NAS
    shell: "shutdown -h now"
    when: inventory_hostname == nas01.kywa.io
