---
###
# Playbook will restore a Plex Media Server
###

- hosts: plex
  gather_facts: false
  tasks:
  - name: ovirt-auth
    import_role:
      name: ovirt

  - name: create-vm
    import_role:
      name: ovirt
      tasks_from: create-vm.yml

  - name: Install Plex RPM
    yum:
      name: /plex/pms-latest.rpm
      state: present

  - name: Restore Systemd unit
    copy:
      remote_src: yes
      src: /plex/plexmediaserver.service
      dest: "{{ systemd_unit_file }}"

  - name: Restore Plex Library data
    unarchive:
      remote_src: yes
      src: "/plex/libbackup.tgz"
      dest: "{{ plex_library_dir }}"

  - name: Restart Plex Service
    systemd:
      name: plexmediaserver
      state: restarted

  collections:
  - ovirt.ovirt
